### ISSUE TITLE
AlertDialogを表示するときにめちゃくちゃ怒られる

### ISSUE THREAD

**Issue by loxygenK** [isso0424/gakkouike#23]
### †Imaginary Protocol† (再現方法)
① カレンダーを表示して日付をタップするか、メインメニューの削除ボタンを押します
② ァ！
### メッセージ
```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
RenderViewport does not support returning intrinsic dimensions.

Calculating the intrinsic dimensions would require instantiating every child of the viewport, which defeats the point of viewports being lazy.

If you are merely trying to shrink-wrap the viewport in the main axis direction, consider a RenderShrinkWrappingViewport render object (ShrinkWrappingViewport widget), which achieves that effect without implementing the intrinsic dimension API.

The relevant error-causing widget was: 
  AlertDialog file:///home/loxygen/StudioProjects/gakkouike/lib/main.dart:55:26
When the exception was thrown, this was the stack: 
#0      RenderViewportBase.debugThrowIfNotCheckingIntrinsics.<anonymous closure> (package:flutter/src/rendering/viewport.dart:299:9)
#1      RenderViewportBase.debugThrowIfNotCheckingIntrinsics (package:flutter/src/rendering/viewport.dart:313:6)
#2      RenderViewportBase.computeMaxIntrinsicWidth (package:flutter/src/rendering/viewport.dart:325:12)
#3      RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1296:23)
#4      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by isso0424** [comment]
工ｴｴｪｪ(´д｀)ｪｪｴｴ工

**Comment by loxygenK** [comment]
俺もわかんね
そっちで再現できますか…?できなかったらめちゃくちゃめんどくさい

**Comment by isso0424** [comment]
てかカレンダーの削除ボタン is 何？

**Comment by loxygenK** [comment]
日本語のクソなところが出てしまったすまんこ

**Comment by isso0424** [comment]
![Screenshot_20200302-124521](https://user-images.githubusercontent.com/49902177/75643890-b7106e80-5c83-11ea-81ed-076f5c9b5d1c.png)
でん

**Comment by isso0424** [comment]
前のデータが残ってた図

**Comment by loxygenK** [comment]
消゛し゛て゛く゛だ゛さ゛い゛

**Comment by loxygenK** [comment]
ところで私は全知全能の神なので修復方法がわかりました
`alertdlg-bugfix`ブランチで神の遊戯を執り行います

**Comment by isso0424** [comment]
エラー吐かない（）

**Comment by loxygenK** [comment]
は、キレた

**Comment by isso0424** [comment]
†再現不可†

**Comment by loxygenK** [comment]
PRを投げました
対戦よろしくお願いします

**Comment by loxygenK** [comment]
**スマートデリートをオフにしないと再現できない** ことを伝え忘れました
どうもカスです

**Comment by isso0424** [comment]
とじる
